### ISSUE TITLE
File names inappropriately validated as urls

### ISSUE THREAD

**Issue by adarsh** [gabebw/croniker#52]
![image](https://cloud.githubusercontent.com/assets/913757/15494088/36331e82-213d-11e6-95c7-21fc88158d7e.jpeg)
![image](https://cloud.githubusercontent.com/assets/913757/15494129/78b6da0a-213d-11e6-90a1-38bbd45ff9bc.jpeg)

**Comment by gabebw** [comment]
Thanks for reporting this! Croniker assumes that a dot followed by [any 3 alphanumeric characters](https://github.com/gabebw/croniker/blob/1ded3b4fbe452a7964be0b299116e4da0f944624/src/Croniker/UrlParser.hs#L27-L30) are TLDs, because that was easier than maintaining a database of actual TLDs.

But now I think the time for actual TLD matching has come.

**Comment by gabebw** [comment]
Heyyy: https://hackage.haskell.org/package/tld

Source: https://github.com/jprider63/tld/blob/master/src/Network/URI/TLD.hs

**Comment by gabebw** [comment]
🎉 This is live on production 🎉

http://croniker.io/

**Comment by adarsh** [comment]
:sparkles:



-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal
